sass:
  load_paths:
    - _sass
    - node_modules/bootstrap/scss
collections:
  authors:
include: ["node_modules"]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Yan's Life]
description: [This site is personal life snapshots of Yan Wang]