sass:
  load_paths:
    - _sass
    - node_modules/bootstrap/scss

collections:
  authors:

include: ["node_modules"]

title: "Yan's Life"
description: "Personal life snapshots of Yan Wang"

plugins: []